INSERT INTO category (category_name) VALUES ('Aquarium furniture');
INSERT INTO category (category_name) VALUES ('Bamboo furniture');
INSERT INTO category (category_name) VALUES ('Bar furniture');
INSERT INTO category (category_name) VALUES ('Bedrooms');
INSERT INTO category (category_name) VALUES ('Casegoods');
INSERT INTO category (category_name) VALUES ('Childrens furniture');
INSERT INTO category (category_name) VALUES ('Concrete furniture');
INSERT INTO category (category_name) VALUES ('Couches and Sofas');
INSERT INTO category (category_name) VALUES ('Decorative arts');
INSERT INTO category (category_name) VALUES ('Door furniture');
INSERT INTO category (category_name) VALUES ('Entertainment');
INSERT INTO category (category_name) VALUES ('Glass furniture');
INSERT INTO category (category_name) VALUES ('Hutch');
INSERT INTO category (category_name) VALUES ('List of chairs');
INSERT INTO category (category_name) VALUES ('Living room');
INSERT INTO category (category_name) VALUES ('Metal furniture');
INSERT INTO category (category_name) VALUES ('Occasional furniture');
INSERT INTO category (category_name) VALUES ('Outdoor Furniture');
INSERT INTO category (category_name) VALUES ('Park furniture ');
INSERT INTO category (category_name) VALUES ('Pet Furniture');
INSERT INTO category (category_name) VALUES ('Sets');
INSERT INTO category (category_name) VALUES ('Sleeping or laying');
INSERT INTO category (category_name) VALUES ('Stadium seating');
INSERT INTO category (category_name) VALUES ('Storage');
INSERT INTO category (category_name) VALUES ('Street furniture');
INSERT INTO category (category_name) VALUES ('Sword furniture');
INSERT INTO category (category_name) VALUES ('Tables');
INSERT INTO category (category_name) VALUES ('Wicker or rattan furniture');
INSERT INTO category (category_name) VALUES ('Wood finishing');
INSERT INTO category (category_name) VALUES ('Wooden furniture');
