INSERT INTO city (city_name, state, city_population) VALUES ('Akron', 'MO', '7684915');
INSERT INTO city (city_name, state, city_population) VALUES ('Akron', 'OH', '5947796');
INSERT INTO city (city_name, state, city_population) VALUES ('Akron', 'RI', '3878285');
INSERT INTO city (city_name, state, city_population) VALUES ('Albuquerque', 'NV', '3608365');
INSERT INTO city (city_name, state, city_population) VALUES ('Albuquerque', 'OR', '6610173');
INSERT INTO city (city_name, state, city_population) VALUES ('Albuquerque', 'WV', '4126810');
INSERT INTO city (city_name, state, city_population) VALUES ('Anaheim', 'CA', '6607294');
INSERT INTO city (city_name, state, city_population) VALUES ('Anaheim', 'HI', '2075107');
INSERT INTO city (city_name, state, city_population) VALUES ('Anaheim', 'KS', '5697569');
INSERT INTO city (city_name, state, city_population) VALUES ('Anchorage', 'FL', '6784867');
INSERT INTO city (city_name, state, city_population) VALUES ('Anchorage', 'MO', '5670054');
INSERT INTO city (city_name, state, city_population) VALUES ('Anchorage', 'MT', '1817211');
INSERT INTO city (city_name, state, city_population) VALUES ('Arlington', 'CA', '186497');
INSERT INTO city (city_name, state, city_population) VALUES ('Arlington', 'KS', '8824634');
INSERT INTO city (city_name, state, city_population) VALUES ('Arlington', 'WA', '4590795');
INSERT INTO city (city_name, state, city_population) VALUES ('Atlanta', 'AR', '362177');
INSERT INTO city (city_name, state, city_population) VALUES ('Atlanta', 'MN', '9791703');
INSERT INTO city (city_name, state, city_population) VALUES ('Atlanta', 'TX', '5727249');
INSERT INTO city (city_name, state, city_population) VALUES ('Aurora', 'NY', '6387356');
INSERT INTO city (city_name, state, city_population) VALUES ('Aurora', 'WA', '6606856');
INSERT INTO city (city_name, state, city_population) VALUES ('Austin', 'AR', '11892016');
INSERT INTO city (city_name, state, city_population) VALUES ('Austin', 'TX', '2853640');
INSERT INTO city (city_name, state, city_population) VALUES ('Austin', 'VT', '8950617');
INSERT INTO city (city_name, state, city_population) VALUES ('Bakersfield', 'CA', '2040079');
INSERT INTO city (city_name, state, city_population) VALUES ('Bakersfield', 'KS', '7086815');
INSERT INTO city (city_name, state, city_population) VALUES ('Baltimore', 'NC', '3909086');
INSERT INTO city (city_name, state, city_population) VALUES ('Baltimore', 'VT', '4944371');
INSERT INTO city (city_name, state, city_population) VALUES ('Baltimore', 'WY', '3411447');
INSERT INTO city (city_name, state, city_population) VALUES ('Baton Rouge', 'AZ', '8041780');
INSERT INTO city (city_name, state, city_population) VALUES ('Baton Rouge', 'DE', '982389');
INSERT INTO city (city_name, state, city_population) VALUES ('Baton Rouge', 'GA', '1189996');
INSERT INTO city (city_name, state, city_population) VALUES ('Birmingham', 'TX', '6323271');
INSERT INTO city (city_name, state, city_population) VALUES ('Birmingham', 'VT', '7239195');
INSERT INTO city (city_name, state, city_population) VALUES ('Birmingham', 'WY', '6407747');
INSERT INTO city (city_name, state, city_population) VALUES ('Boston', 'CO', '11235916');
INSERT INTO city (city_name, state, city_population) VALUES ('Boston', 'NV', '9761036');
INSERT INTO city (city_name, state, city_population) VALUES ('Boston', 'WV', '2211765');
INSERT INTO city (city_name, state, city_population) VALUES ('Buffalo', 'AL', '6568145');
INSERT INTO city (city_name, state, city_population) VALUES ('Buffalo', 'IA', '9513968');
INSERT INTO city (city_name, state, city_population) VALUES ('Charlotte', 'CA', '1055095');
INSERT INTO city (city_name, state, city_population) VALUES ('Charlotte', 'NY', '7082890');
INSERT INTO city (city_name, state, city_population) VALUES ('Charlotte', 'WA', '11640843');
INSERT INTO city (city_name, state, city_population) VALUES ('Chicago', 'MI', '2519487');
INSERT INTO city (city_name, state, city_population) VALUES ('Chicago', 'NH', '7223750');
INSERT INTO city (city_name, state, city_population) VALUES ('Cincinnati', 'CO', '5894247');
INSERT INTO city (city_name, state, city_population) VALUES ('Cincinnati', 'MA', '474864');
INSERT INTO city (city_name, state, city_population) VALUES ('Cincinnati', 'WV', '5880905');
INSERT INTO city (city_name, state, city_population) VALUES ('Cleveland', 'CT', '5507665');
INSERT INTO city (city_name, state, city_population) VALUES ('Cleveland', 'IL', '9953124');
INSERT INTO city (city_name, state, city_population) VALUES ('Cleveland', 'OK', '10747084');
INSERT INTO city (city_name, state, city_population) VALUES ('Colorado', 'AZ', '2409313');
INSERT INTO city (city_name, state, city_population) VALUES ('Colorado', 'DE', '4478196');
INSERT INTO city (city_name, state, city_population) VALUES ('Colorado', 'MD', '8013845');
INSERT INTO city (city_name, state, city_population) VALUES ('Columbus', 'ID', '2217539');
INSERT INTO city (city_name, state, city_population) VALUES ('Columbus', 'IL', '970026');
INSERT INTO city (city_name, state, city_population) VALUES ('Corpus Christi', 'IN', '7798000');
INSERT INTO city (city_name, state, city_population) VALUES ('Corpus Christi', 'LA', '11913487');
INSERT INTO city (city_name, state, city_population) VALUES ('Corpus Christi', 'NE', '7966699');
INSERT INTO city (city_name, state, city_population) VALUES ('Dallas', 'CT', '8905844');
INSERT INTO city (city_name, state, city_population) VALUES ('Dallas', 'OK', '8015731');
INSERT INTO city (city_name, state, city_population) VALUES ('Dallas', 'WI', '1267701');
INSERT INTO city (city_name, state, city_population) VALUES ('Dayton', 'IL', '5242806');
INSERT INTO city (city_name, state, city_population) VALUES ('Dayton', 'OK', '7083222');
INSERT INTO city (city_name, state, city_population) VALUES ('Denver', 'NV', '8746205');
INSERT INTO city (city_name, state, city_population) VALUES ('Denver', 'WV', '11761169');
INSERT INTO city (city_name, state, city_population) VALUES ('Des Moines', 'NC', '11838579');
INSERT INTO city (city_name, state, city_population) VALUES ('Des Moines', 'OH', '221583');
INSERT INTO city (city_name, state, city_population) VALUES ('Des Moines', 'RI', '1615094');
INSERT INTO city (city_name, state, city_population) VALUES ('Detroit', 'KY', '6452123');
INSERT INTO city (city_name, state, city_population) VALUES ('Detroit', 'MN', '9377710');
INSERT INTO city (city_name, state, city_population) VALUES ('Detroit', 'VA', '5859113');
INSERT INTO city (city_name, state, city_population) VALUES ('El Paso', 'FL', '9857482');
INSERT INTO city (city_name, state, city_population) VALUES ('El Paso', 'MO', '8384616');
INSERT INTO city (city_name, state, city_population) VALUES ('El Paso', 'OH', '1609323');
INSERT INTO city (city_name, state, city_population) VALUES ('Fort Wayne', 'AZ', '6711652');
INSERT INTO city (city_name, state, city_population) VALUES ('Fort Wayne', 'DE', '5063405');
INSERT INTO city (city_name, state, city_population) VALUES ('Fort Worth', 'CO', '8277959');
INSERT INTO city (city_name, state, city_population) VALUES ('Fort Worth', 'MA', '2926957');
INSERT INTO city (city_name, state, city_population) VALUES ('Fort Worth', 'UT', '1067737');
INSERT INTO city (city_name, state, city_population) VALUES ('Fremont', 'ID', '4567408');
INSERT INTO city (city_name, state, city_population) VALUES ('Fremont', 'PA', '10148986');
INSERT INTO city (city_name, state, city_population) VALUES ('Fresno', 'MA', '8117');
INSERT INTO city (city_name, state, city_population) VALUES ('Fresno', 'UT', '10820299');
INSERT INTO city (city_name, state, city_population) VALUES ('Garland', 'IA', '526447');
INSERT INTO city (city_name, state, city_population) VALUES ('Garland', 'SD', '3528912');
INSERT INTO city (city_name, state, city_population) VALUES ('Glendale', 'CT', '6682429');
INSERT INTO city (city_name, state, city_population) VALUES ('Glendale', 'WI', '6186100');
INSERT INTO city (city_name, state, city_population) VALUES ('Grand Rapids', 'FL', '1293704');
INSERT INTO city (city_name, state, city_population) VALUES ('Grand Rapids', 'MO', '8303138');
INSERT INTO city (city_name, state, city_population) VALUES ('Grand Rapids', 'OH', '5388088');
INSERT INTO city (city_name, state, city_population) VALUES ('Greensboro', 'MO', '7616852');
INSERT INTO city (city_name, state, city_population) VALUES ('Greensboro', 'OH', '106999');
INSERT INTO city (city_name, state, city_population) VALUES ('Greensboro', 'RI', '8379650');
INSERT INTO city (city_name, state, city_population) VALUES ('Hialeah', 'HI', '6777174');
INSERT INTO city (city_name, state, city_population) VALUES ('Hialeah', 'KS', '9384901');
INSERT INTO city (city_name, state, city_population) VALUES ('Hialeah', 'NM', '6903443');
INSERT INTO city (city_name, state, city_population) VALUES ('Honolulu', 'GA', '11804872');
INSERT INTO city (city_name, state, city_population) VALUES ('Honolulu', 'WI', '3451405');
INSERT INTO city (city_name, state, city_population) VALUES ('Houston', 'NJ', '1247696');
INSERT INTO city (city_name, state, city_population) VALUES ('Houston', 'OR', '1117744');
INSERT INTO city (city_name, state, city_population) VALUES ('Indianapolis', 'IN', '5746277');
INSERT INTO city (city_name, state, city_population) VALUES ('Indianapolis', 'MS', '3631974');
INSERT INTO city (city_name, state, city_population) VALUES ('Indianapolis', 'NE', '11698053');
INSERT INTO city (city_name, state, city_population) VALUES ('Jackson', 'AZ', '11301894');
INSERT INTO city (city_name, state, city_population) VALUES ('Jackson', 'MD', '9028542');
INSERT INTO city (city_name, state, city_population) VALUES ('Jacksonville', 'MI', '10133769');
INSERT INTO city (city_name, state, city_population) VALUES ('Jacksonville', 'NH', '11372286');
INSERT INTO city (city_name, state, city_population) VALUES ('Jacksonville', 'TN', '6911804');
INSERT INTO city (city_name, state, city_population) VALUES ('Jersey', 'NC', '2058323');
INSERT INTO city (city_name, state, city_population) VALUES ('Jersey', 'VT', '3635902');
INSERT INTO city (city_name, state, city_population) VALUES ('Jersey', 'WY', '8629505');
INSERT INTO city (city_name, state, city_population) VALUES ('Kansas', 'ME', '10349326');
INSERT INTO city (city_name, state, city_population) VALUES ('Kansas', 'MI', '9927560');
INSERT INTO city (city_name, state, city_population) VALUES ('Kansas', 'NH', '11239032');
INSERT INTO city (city_name, state, city_population) VALUES ('Las Vegas', 'AL', '10190906');
INSERT INTO city (city_name, state, city_population) VALUES ('Las Vegas', 'ME', '4037431');
INSERT INTO city (city_name, state, city_population) VALUES ('Las Vegas', 'NH', '4891719');
INSERT INTO city (city_name, state, city_population) VALUES ('Lincoln', 'AR', '5878938');
INSERT INTO city (city_name, state, city_population) VALUES ('Lincoln', 'MN', '10497740');
INSERT INTO city (city_name, state, city_population) VALUES ('Lincoln', 'TX', '9334504');
INSERT INTO city (city_name, state, city_population) VALUES ('Little Rock', 'AR', '11344715');
INSERT INTO city (city_name, state, city_population) VALUES ('Little Rock', 'MN', '2785238');
INSERT INTO city (city_name, state, city_population) VALUES ('Little Rock', 'VA', '9000407');
INSERT INTO city (city_name, state, city_population) VALUES ('Long Beach', 'MI', '8263969');
INSERT INTO city (city_name, state, city_population) VALUES ('Long Beach', 'TN', '7359630');
INSERT INTO city (city_name, state, city_population) VALUES ('Los Angeles', 'HI', '9458934');
INSERT INTO city (city_name, state, city_population) VALUES ('Los Angeles', 'KS', '1020310');
INSERT INTO city (city_name, state, city_population) VALUES ('Louisville', 'AK', '9425982');
INSERT INTO city (city_name, state, city_population) VALUES ('Louisville', 'ID', '683604');
INSERT INTO city (city_name, state, city_population) VALUES ('Louisville', 'PA', '6144849');
INSERT INTO city (city_name, state, city_population) VALUES ('Lubbock', 'ID', '9938640');
INSERT INTO city (city_name, state, city_population) VALUES ('Lubbock', 'IL', '7457644');
INSERT INTO city (city_name, state, city_population) VALUES ('Lubbock', 'PA', '10361209');
INSERT INTO city (city_name, state, city_population) VALUES ('Madison', 'IA', '3809269');
INSERT INTO city (city_name, state, city_population) VALUES ('Madison', 'SC', '7693110');
INSERT INTO city (city_name, state, city_population) VALUES ('Madison', 'SD', '122326');
INSERT INTO city (city_name, state, city_population) VALUES ('Memphis', 'FL', '10955694');
INSERT INTO city (city_name, state, city_population) VALUES ('Memphis', 'MT', '6614192');
INSERT INTO city (city_name, state, city_population) VALUES ('Mesa', 'AK', '9259541');
INSERT INTO city (city_name, state, city_population) VALUES ('Mesa', 'ND', '3525057');
INSERT INTO city (city_name, state, city_population) VALUES ('Miami', 'MT', '2867463');
INSERT INTO city (city_name, state, city_population) VALUES ('Miami', 'NY', '893856');
INSERT INTO city (city_name, state, city_population) VALUES ('Miami', 'WA', '10058645');
INSERT INTO city (city_name, state, city_population) VALUES ('Milwaukee', 'MT', '8177407');
INSERT INTO city (city_name, state, city_population) VALUES ('Milwaukee', 'NY', '2446782');
INSERT INTO city (city_name, state, city_population) VALUES ('Minneapolis', 'NJ', '6588284');
INSERT INTO city (city_name, state, city_population) VALUES ('Minneapolis', 'NV', '1285783');
INSERT INTO city (city_name, state, city_population) VALUES ('Minneapolis', 'OR', '1559327');
INSERT INTO city (city_name, state, city_population) VALUES ('Mobile', 'NC', '655603');
INSERT INTO city (city_name, state, city_population) VALUES ('Mobile', 'OH', '9790261');
INSERT INTO city (city_name, state, city_population) VALUES ('Mobile', 'RI', '4854095');
INSERT INTO city (city_name, state, city_population) VALUES ('Montgomery', 'KY', '7420175');
INSERT INTO city (city_name, state, city_population) VALUES ('Montgomery', 'SC', '6239429');
INSERT INTO city (city_name, state, city_population) VALUES ('Montgomery', 'VA', '11172589');
INSERT INTO city (city_name, state, city_population) VALUES ('Nashville', 'IN', '6084440');
INSERT INTO city (city_name, state, city_population) VALUES ('Nashville', 'LA', '3985400');
INSERT INTO city (city_name, state, city_population) VALUES ('Nashville', 'UT', '9753958');
INSERT INTO city (city_name, state, city_population) VALUES ('New Orleans', 'IN', '10238768');
INSERT INTO city (city_name, state, city_population) VALUES ('New Orleans', 'LA', '6989138');
INSERT INTO city (city_name, state, city_population) VALUES ('New York', 'AR', '6259301');
INSERT INTO city (city_name, state, city_population) VALUES ('New York', 'TX', '2901954');
INSERT INTO city (city_name, state, city_population) VALUES ('New York', 'VT', '9681671');
INSERT INTO city (city_name, state, city_population) VALUES ('Newark', 'DE', '11606155');
INSERT INTO city (city_name, state, city_population) VALUES ('Newark', 'GA', '6254424');
INSERT INTO city (city_name, state, city_population) VALUES ('Norfolk', 'FL', '8985009');
INSERT INTO city (city_name, state, city_population) VALUES ('Norfolk', 'MT', '5256933');
INSERT INTO city (city_name, state, city_population) VALUES ('Norfolk', 'NY', '10795717');
INSERT INTO city (city_name, state, city_population) VALUES ('Oakland', 'ME', '7169735');
INSERT INTO city (city_name, state, city_population) VALUES ('Oakland', 'NH', '9444807');
INSERT INTO city (city_name, state, city_population) VALUES ('Oklahoma', 'AK', '9889246');
INSERT INTO city (city_name, state, city_population) VALUES ('Oklahoma', 'ND', '8640549');
INSERT INTO city (city_name, state, city_population) VALUES ('Oklahoma', 'NM', '6526590');
INSERT INTO city (city_name, state, city_population) VALUES ('Omaha', 'AZ', '1994293');
INSERT INTO city (city_name, state, city_population) VALUES ('Omaha', 'MD', '5500143');
INSERT INTO city (city_name, state, city_population) VALUES ('Omaha', 'MS', '7524170');
INSERT INTO city (city_name, state, city_population) VALUES ('Philadelphia', 'FL', '6389592');
INSERT INTO city (city_name, state, city_population) VALUES ('Philadelphia', 'MO', '3840977');
INSERT INTO city (city_name, state, city_population) VALUES ('Phoenix', 'DE', '164250');
INSERT INTO city (city_name, state, city_population) VALUES ('Phoenix', 'GA', '9021855');
INSERT INTO city (city_name, state, city_population) VALUES ('Phoenix', 'WI', '1105394');
INSERT INTO city (city_name, state, city_population) VALUES ('Pittsburgh', 'CO', '1709398');
INSERT INTO city (city_name, state, city_population) VALUES ('Pittsburgh', 'WV', '4898046');
INSERT INTO city (city_name, state, city_population) VALUES ('Portland', 'IN', '5932588');
INSERT INTO city (city_name, state, city_population) VALUES ('Portland', 'NE', '4812844');
INSERT INTO city (city_name, state, city_population) VALUES ('Raleigh', 'NJ', '1703543');
INSERT INTO city (city_name, state, city_population) VALUES ('Raleigh', 'OR', '339737');
INSERT INTO city (city_name, state, city_population) VALUES ('Raleigh', 'TN', '8307760');
INSERT INTO city (city_name, state, city_population) VALUES ('Richmond', 'AK', '6544852');
INSERT INTO city (city_name, state, city_population) VALUES ('Richmond', 'ND', '5705182');
INSERT INTO city (city_name, state, city_population) VALUES ('Richmond', 'PA', '9488065');
INSERT INTO city (city_name, state, city_population) VALUES ('Riverside', 'NC', '1681261');
INSERT INTO city (city_name, state, city_population) VALUES ('Riverside', 'RI', '8563087');
INSERT INTO city (city_name, state, city_population) VALUES ('Riverside', 'WY', '11949994');
INSERT INTO city (city_name, state, city_population) VALUES ('Rochester', 'NV', '7234299');
INSERT INTO city (city_name, state, city_population) VALUES ('Rochester', 'OR', '3486778');
INSERT INTO city (city_name, state, city_population) VALUES ('Sacramento', 'CA', '5513783');
INSERT INTO city (city_name, state, city_population) VALUES ('Sacramento', 'WA', '9567383');
INSERT INTO city (city_name, state, city_population) VALUES ('San Antonio', 'MD', '4968774');
INSERT INTO city (city_name, state, city_population) VALUES ('San Antonio', 'MS', '10495370');
INSERT INTO city (city_name, state, city_population) VALUES ('San Diego', 'AL', '194470');
INSERT INTO city (city_name, state, city_population) VALUES ('San Diego', 'IA', '817541');
INSERT INTO city (city_name, state, city_population) VALUES ('San Diego', 'SD', '6839401');
INSERT INTO city (city_name, state, city_population) VALUES ('San Francisco', 'MD', '7820706');
INSERT INTO city (city_name, state, city_population) VALUES ('San Francisco', 'MS', '2791355');
INSERT INTO city (city_name, state, city_population) VALUES ('San Francisco', 'NE', '8303440');
INSERT INTO city (city_name, state, city_population) VALUES ('San Jose', 'AL', '11877303');
INSERT INTO city (city_name, state, city_population) VALUES ('San Jose', 'IA', '7025397');
INSERT INTO city (city_name, state, city_population) VALUES ('San Jose', 'ME', '8713838');
INSERT INTO city (city_name, state, city_population) VALUES ('Santa Ana', 'LA', '7542170');
INSERT INTO city (city_name, state, city_population) VALUES ('Santa Ana', 'UT', '11641031');
INSERT INTO city (city_name, state, city_population) VALUES ('Seattle', 'HI', '6342350');
INSERT INTO city (city_name, state, city_population) VALUES ('Seattle', 'ND', '8919255');
INSERT INTO city (city_name, state, city_population) VALUES ('Seattle', 'NM', '4576392');
INSERT INTO city (city_name, state, city_population) VALUES ('Shreveport', 'TX', '6768568');
INSERT INTO city (city_name, state, city_population) VALUES ('Shreveport', 'VT', '7695528');
INSERT INTO city (city_name, state, city_population) VALUES ('Shreveport', 'WY', '2420369');
INSERT INTO city (city_name, state, city_population) VALUES ('Spokane', 'NJ', '636286');
INSERT INTO city (city_name, state, city_population) VALUES ('Spokane', 'TN', '4281152');
INSERT INTO city (city_name, state, city_population) VALUES ('St. Louis', 'NC', '7594582');
INSERT INTO city (city_name, state, city_population) VALUES ('St. Louis', 'RI', '595768');
INSERT INTO city (city_name, state, city_population) VALUES ('St. Louis', 'WY', '145689');
INSERT INTO city (city_name, state, city_population) VALUES ('St. Paul', 'CT', '5161245');
INSERT INTO city (city_name, state, city_population) VALUES ('St. Paul', 'GA', '4562887');
INSERT INTO city (city_name, state, city_population) VALUES ('St. Paul', 'WI', '11310912');
INSERT INTO city (city_name, state, city_population) VALUES ('St. Petersburg', 'CT', '4843309');
INSERT INTO city (city_name, state, city_population) VALUES ('St. Petersburg', 'OK', '5367444');
INSERT INTO city (city_name, state, city_population) VALUES ('Stockton', 'ND', '11526559');
INSERT INTO city (city_name, state, city_population) VALUES ('Stockton', 'NM', '8214688');
INSERT INTO city (city_name, state, city_population) VALUES ('Tacoma', 'ID', '4181984');
INSERT INTO city (city_name, state, city_population) VALUES ('Tacoma', 'IL', '10845187');
INSERT INTO city (city_name, state, city_population) VALUES ('Tacoma', 'OK', '6965826');
INSERT INTO city (city_name, state, city_population) VALUES ('Tampa', 'MS', '9296125');
INSERT INTO city (city_name, state, city_population) VALUES ('Tampa', 'NE', '8901528');
INSERT INTO city (city_name, state, city_population) VALUES ('Toledo', 'KY', '6662145');
INSERT INTO city (city_name, state, city_population) VALUES ('Toledo', 'SC', '7049801');
INSERT INTO city (city_name, state, city_population) VALUES ('Toledo', 'SD', '8377152');
INSERT INTO city (city_name, state, city_population) VALUES ('Tucson', 'MI', '8142328');
INSERT INTO city (city_name, state, city_population) VALUES ('Tucson', 'NJ', '2745552');
INSERT INTO city (city_name, state, city_population) VALUES ('Tucson', 'TN', '11958750');
INSERT INTO city (city_name, state, city_population) VALUES ('Tulsa', 'HI', '8783024');
INSERT INTO city (city_name, state, city_population) VALUES ('Tulsa', 'NM', '8908456');
INSERT INTO city (city_name, state, city_population) VALUES ('Virginia Beach', 'CO', '5821114');
INSERT INTO city (city_name, state, city_population) VALUES ('Virginia Beach', 'MA', '5134235');
INSERT INTO city (city_name, state, city_population) VALUES ('Washington', 'AL', '7089351');
INSERT INTO city (city_name, state, city_population) VALUES ('Washington', 'ME', '1384044');
INSERT INTO city (city_name, state, city_population) VALUES ('Wichita', 'AK', '6134430');
INSERT INTO city (city_name, state, city_population) VALUES ('Wichita', 'PA', '11803323');
INSERT INTO city (city_name, state, city_population) VALUES ('Yonkers', 'LA', '10868202');
INSERT INTO city (city_name, state, city_population) VALUES ('Yonkers', 'MA', '8672133');
INSERT INTO city (city_name, state, city_population) VALUES ('Yonkers', 'UT', '116283');
