INSERT INTO holiday (Date, holiday_name) VALUES ('2009-05-25', 'Memorial Day');
INSERT INTO holiday (Date, holiday_name) VALUES ('2011-01-01', 'New Year''s Day');
INSERT INTO holiday (Date, holiday_name) VALUES ('2011-01-17', 'Martin Luther King Jr. Day');
INSERT INTO holiday (Date, holiday_name) VALUES ('2011-02-21', 'President''s Day');
INSERT INTO holiday (Date, holiday_name) VALUES ('2011-05-30', 'Memorial Day');
INSERT INTO holiday (Date, holiday_name) VALUES ('2011-07-04', 'Independence Day');
INSERT INTO holiday (Date, holiday_name) VALUES ('2011-09-05', 'Labor Day');
INSERT INTO holiday (Date, holiday_name) VALUES ('2011-11-11', 'Veteran''s Day');
INSERT INTO holiday (Date, holiday_name) VALUES ('2011-11-24', 'Thanksgiving');
INSERT INTO holiday (Date, holiday_name) VALUES ('2011-11-25', 'Thanksgiving');
INSERT INTO holiday (Date, holiday_name) VALUES ('2011-12-25', 'Christmas Day');
INSERT INTO holiday (Date, holiday_name) VALUES ('2012-01-01', 'New Year''s Day');
INSERT INTO holiday (Date, holiday_name) VALUES ('2012-01-02', 'New Year''s Day');
INSERT INTO holiday (Date, holiday_name) VALUES ('2012-01-16', 'Martin Luther King Jr. Day');
INSERT INTO holiday (Date, holiday_name) VALUES ('2012-02-20', 'President''s Day');
INSERT INTO holiday (Date, holiday_name) VALUES ('2012-05-28', 'Memorial Day');
